#Configuración de la aplicación
#Mon Dec 08 19:34:27 CET 2025
app.debug=false
app.idioma=es
app.titulo=Aplicaci\u00F3n de ejemplo
app.version=1.0.0
db.host=localhost
db.name=Base_de_datos_inventada
db.password=contrase\u00F1a
db.port=3307
db.user=administrador
ui.tamano_fuente=11
ui.tema=oscuro
